 
#pragma output CRT_ORG_CODE = 0
#pragma output CRT_INCLUDE_PREAMBLE = 0
#pragma output CRT_ORG_DATA = 0x2000
#pragma output CRT_MODEL = 1
#pragma output REGISTER_SP = 0x4000
#pragma output CRT_STACK_SIZE = 256
#pragma output CLIB_MALLOC_HEAP_SIZE = 0
#pragma output CLIB_STDIO_HEAP_SIZE = 0
//#pragma output CRT_ORG_VECTOR_TABLE = -0x100
//#pragma output CRT_ENABLE_RST = 0x80
//#pragma output CRT_ENABLE_EIDI = 0x03
//#pragma output CRT_INTERRUPT_MODE = 0
